# Generated by Django 5.0.2 on 2024-03-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Register',
        ),
    ]
