# Generated by Django 5.0 on 2024-03-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFinanceApp', '0004_amounttype_expancesource_incomesource'),
        ('FinanceApp', '0019_remove_expance_amount_sourse_remove_expance_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Register',
        ),
        migrations.DeleteModel(
            name='Amounttype',
        ),
        migrations.DeleteModel(
            name='Expancesource',
        ),
        migrations.DeleteModel(
            name='Incomesource',
        ),
    ]
