# Generated by Django 5.0 on 2024-02-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Register',
        ),
    ]
