# Generated by Django 5.0 on 2024-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinanceApp', '0002_delete_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Mobile_no', models.BigIntegerField()),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
