# Generated by Django 5.0 on 2024-03-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='Saved_amount',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goals',
            name='Target_amount',
            field=models.CharField(max_length=200),
        ),
    ]
