# Generated by Django 5.0.2 on 2024-03-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='expance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='average',
            name='income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expance',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
