# Generated by Django 5.0 on 2024-03-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0008_alter_goals_saved_amount_alter_goals_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='Saved_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='goals',
            name='Target_amount',
            field=models.BigIntegerField(),
        ),
    ]
