# Generated by Django 5.0 on 2024-03-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0010_alter_goals_targe_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
