# Generated by Django 5.0 on 2024-03-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_initial'),
        ('FinanceApp', '0012_goals'),
    ]

    operations = [
    ]
