<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-21 06:46
=======
# Generated by Django 5.0 on 2024-03-21 06:29
>>>>>>> bc26eaf58bb0240d0f4635809f0a0357b926c5ce

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_initial'),
        ('FinanceApp', '0012_goals'),
    ]

    operations = [
    ]
