# Generated by Django 5.0 on 2024-03-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0013_merge_0009_initial_0012_goals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
