# Generated by Django 5.0.2 on 2024-03-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0013_merge_0009_initial_0012_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='expance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='income',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expance',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
