# Generated by Django 5.0.2 on 2024-03-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0014_alter_average_expance_alter_average_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='expance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='average',
            name='income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expance',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_name', models.CharField(max_length=200)),
                ('Target_amount', models.BigIntegerField()),
                ('Saved_amount', models.BigIntegerField()),
                ('Targe_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.user_register')),
            ],
        ),
    ]
