# Generated by Django 5.0 on 2024-03-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
