# Generated by Django 5.0 on 2024-03-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0020_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
