# Generated by Django 5.0.2 on 2024-03-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFinanceApp', '0006_initial'),
        ('FinanceApp', '0020_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expance',
            name='amount_sourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminFinanceApp.expancesource'),
        ),
    ]
