# Generated by Django 5.0 on 2024-03-23 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0021_delete_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_name', models.CharField(max_length=200)),
                ('Target_amount', models.BigIntegerField()),
                ('Saved_amount', models.BigIntegerField()),
                ('Targe_date', models.DateField()),
                ('per', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.user_register')),
            ],
        ),
    ]
