# Generated by Django 5.0 on 2024-03-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0022_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='per',
            field=models.BigIntegerField(),
        ),
    ]
