# Generated by Django 5.0 on 2024-03-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0023_alter_goals_per'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
